### ISSUE TITLE
Doesn't build without prerequisites not mentioned in Readme

### ISSUE THREAD

**Issue by nain-F49FF806** [cmusatyalab/wireguard4netns#2]
This looks like a pretty interesting project, and I am curious to try it out. 
I think it'd be a good fit for providing networking to unprivileged pet [distroboxes](https://github.com/89luca89/distrobox). 

As I am trying to build this in a fresh environment, the poetry build step fails.
```
[wireguard4netns]$ poetry build

Preparing build environment with build-system requirements poetry-core
Building wireguard4netns (0.1.3.post.dev0)
Downloading golang-v1.19.4
Copying wireguard-go source
Patching wireguard-go source
Traceback (most recent call last):
  File "/home/example.box/wireguard4netns/build.py", line 147, in <module>
    build()
  File "/home/example.box/wireguard4netns/build.py", line 57, in build
    subprocess.run([patch, "-p1"], stdin=patchfile.open(), cwd=tmp_root, check=True)
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1775, in _execute_child
    and os.path.dirname(executable)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 152, in dirname
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

On inspecting the `build.py` code, and trying to retrace the steps manually, I believe the error is because `go` and `patch` executables are not present.

Perhaps the presence/absence of these can be detected in the script and a warning provided?  
Additionally, it might be a good idea to mention them somewhere in the readme. 

Cheers.

**Comment by jaharkes** [comment]
Ah yes, I definitely should at least mention those build dependencies.

Adding warnings to the build.py should be fairly straightforward because we're already using `shutil.which` to find if we have the necessary binaries and so we can trivially test for none and we don't have to mess with exception handlers around `subprocess.run`. The only thing I would have to check is what the actual poetry/setuptools expectation here is. Do we raise an exception or use sys.exit with some (specific?) non-zero value, etc.

Unless you really need the VPN functionality provided by the WireGuard tunnel, a far more mature and probably stable solution for pet distroboxes would be [slirp4netns](https://github.com/rootless-containers/slirp4netns) which was a huge inspiration for this project. They proved this could even be done without root to begin with and it is more likely already packaged as a pre-compiled binary for various systems.

**Comment by nain-F49FF806** [comment]
Yes, Distrobox already uses [slirp4netns](https://github.com/rootless-containers/slirp4netns) through podman, but this uses the default network interface of host to access the internet at large. 

I was looking at somehow plumbing slirp4netns with user-space WireGuard myself to have a transparent VPN-like functionality for the distroboxes (without root), while keeping the host network unaffected. That's how I came across this project. :)

I did compile and install the cmd line `wireguard4netns` eventually, and iiuc: it should add a tap interface to netns identified by `ns_pid` and route the incoming packets to wireguard peer defined in `wireguard.conf` through a wireguard tunnel over the host interface `interface`. Is this understanding correct?

**Comment by jaharkes** [comment]
Yeah, sounds about right. When the network namespace goes away, the tun/tap interface closes which should trigger the wireguard-go process to quit. I've spun up processes in an isolated network namespace with `unshare` and then attached a tunnel with this to give them network access.
